Trigger onValidate when inital value is set on Select widget
dojo/widgets pull request #1699
Opened 2021-03-23 18:28 UTC by samends

**Type:** bug

**Description:**
`Select` widget was not validating when there was an initial value set. Pending unit test

Resolves #1653

2021-03-23 21:50 UTC, aciccarello approved these changes

2021-03-23 21:50 UTC, aciccarello commented on src/select/index.tsx
> +	if ((required && dirty) || value !== undefined) {
The extra parenthesis shouldn't be necessary
```suggestion
	if (required && dirty || value !== undefined) {
```

2021-03-24 11:56 UTC, tomdye requested changes
I'm not sure this is right as its validating selects even when they are not required and do not require validation.

2021-03-24 13:22 UTC, samends commented
@tomdye this was added so that if there's an initial value set, the `Select` widget will validate it

2021-03-24 14:08 UTC, tomdye commented
@samends I believe that any passed `onValidate` function should be called but if `required` is not set to true it should not validate internally.

2021-03-24 15:01 UTC, tomdye approved these changes

2021-03-24 15:18 UTC, merged