Fix/time picker validate
dojo/widgets pull request #1716
Opened 2021-04-01 20:33 UTC by bitpshr

**Type:** bug

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/framework/blob/master/STYLE.md)
* [ ] Unit tests are included in the PR
* [x] For new widgets, an entry has been added to the `.dojorc`
* [x] For new widgets, `theme.variant()` is added to the root domnode
* [x] Any widget variant uses `theme.compose` like [this](https://github.com/dojo/widgets/issues/847)
* [x] WidgetProperties are exported

**Description:**

This pull request fixes an issue with `TimePicker` that prevented required instances from failing validation.

Resolves #1714

2021-04-01 20:46 UTC, bitpshr commented on src/time-picker/index.tsx
> +			isValid = isValid === undefined ? validationMessages.length === 0 : isValid;
This was the root of the issue: The underlying `TextInput` updates `inputIsValid`, but then local validation and `validationMessages.length` ended up overwriting this before triggering `onValidate`.

2021-04-06 12:53 UTC, tomdye commented
@bitpshr should this be showing as visibly valid, ie. green, when set to required and with a value passed? It appears that it currently does not. Also, it looks like the dojo themed time picker now shows as valid / green as soon as it is rendered even though it's not supposed to.

2021-04-07 14:49 UTC, bitpshr commented
@tomdye: The Material `TimePicker` does not show any valid border in its valid state (and neither do any other inputs, like `TextInput`), so I think we're good there. The Dojo `TimePicker` always showed a green border when initially rendered, and that is not related to these changes, but I can take a look at that as part of this PR.

2021-04-08 15:46 UTC, agubler requested changes
This works for me, I'd like to get @tomdye's approval and also a test to cover the changes?

2021-04-09 16:38 UTC, bitpshr commented
@agubler test added that fails on `master` and passes here, made as simple as possible to show the issue. cc sir @tomdye when you have a chance to sign off.

2021-04-09 17:38 UTC, tomdye commented on src/time-picker/tests/unit/TimePicker.spec.tsx
> +const buttonTemplate = (required?: boolean) =>
test looks good, but we've tried really hard to remove any need for these `getRender` / `getTemplate` functions via the addition of the assertion template so I'd rather we didn't add one here when you could simply to

```
const requiredTemplate = baseTemplate
			.setProperty('@input', 'required', true)
```

2021-04-09 17:40 UTC, tomdye approved these changes
Added a comment re. how `setProperty` should be used on the `baseTemplate`, once that's fixed please merge

2021-04-12 11:05 UTC, merged