1609 - Do not set first item as active by default
dojo/widgets pull request #1724
Opened 2021-04-08 13:56 UTC by KaneFreeman

**Type:** bug

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/framework/blob/master/STYLE.md)
* [x] Unit tests are included in the PR
* [ ] For new widgets, an entry has been added to the `.dojorc`
* [ ] For new widgets, `theme.variant()` is added to the root domnode
* [ ] Any widget variant uses `theme.compose` like [this](https://github.com/dojo/widgets/issues/847)
* [ ] WidgetProperties are exported

**Description:** When no active index is set, no list item is selected instead of the previous behavior of defaulting to the first item.

Resolves #1609

2021-04-09 12:33 UTC, tomdye commented on src/list/index.tsx
> +		const first = computedActiveIndex ? items.slice(0, computedActiveIndex) : [];
if computed active index was `0` wouldn't this be falsey rather than selecting the first item?

2021-04-09 12:40 UTC, tomdye commented on src/list/index.tsx
> +				computedActiveIndex !== undefined
👍 good catch

2021-04-13 09:35 UTC, agubler requested changes
couple small comments

2021-04-13 09:35 UTC, agubler commented on src/list/index.tsx
> +						(computedActiveIndex !== undefined ? computedActiveIndex + 1 : 0) % total
Can we do this outside the function call? It's a bit messy to understand at the moment.

2021-04-13 09:35 UTC, agubler commented on src/list/index.tsx
> +						(computedActiveIndex !== undefined
Same comment re moving the logic out from the function call.

2021-04-14 08:04 UTC, agubler approved these changes

2021-04-14 13:49 UTC, merged